const CriteriaTypes = {
  WORDS_LEARNED: 'WORDS_LEARNED',
  GRAMMAR_COMPLETED: 'GRAMMAR_COMPLETED',
  CORRECT_ANSWERS: 'CORRECT_ANSWERS',
  DAILY_LOGIN: 'DAILY_LOGIN',
  SPEAKING_LEVEL: 'SPEAKING_LEVEL',
  QUESTIONS_ANSWERED: 'QUESTIONS_ANSWERED',
};

module.exports = CriteriaTypes;
