const CriteriaTypes = {
  QUESTIONS_ANSWERED: 'QUESTIONS_ANSWERED',
  CORRECT_ANSWERS: 'CORRECT_ANSWERS',
  INCORRECT_ANSWERS: 'INCORRECT_ANSWERS',
  LESSON_STARTED: 'LESSON_STARTED',
  DAY_STREAK: 'DAY_STREAK',
  NEXT_LEAGUE: 'NEXT_LEAGUE',
};

module.exports = CriteriaTypes;
